# OSS-Fuzz project configuration for mrustc
homepage: "https://github.com/thepowersgang/mrustc"
language: c++
primary_contact: ""
auto_ccs:
  - ""

sanitizers:
  - address
  - undefined

architectures:
  - x86_64

fuzzing_engines:
  - libfuzzer

main_repo: "https://github.com/thepowersgang/mrustc.git"
